import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Digital Drive", // Set the website name here
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Fonts Links */}
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;700&display=swap" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet"/>


        {/* Font Awesome Link */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOMo7bE1P9xL0iw5TOoX2hvMEb0G1D+0D5uV1A"
          crossOrigin="anonymous"
        />
      </head>
      <body style={{ fontFamily: 'Poppins, Nunito, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}
